#!/usr/bin/env python3
"""Turns build/lint/tidy.txt and format-churn.txt into a readable SUMMARY.md."""

import collections
import pathlib
import re
import subprocess
import sys

# Checks that fire on something structural to bare-metal EL2 code rather than on
# a fixable defect. Flagged in the report as candidates for the exclusion list.
BARE_METAL_SUSPECTS = {
    "hicpp-no-assembler",
    "cppcoreguidelines-macro-usage",
    "cppcoreguidelines-macro-to-enum",
    "modernize-macro-to-enum",
    "cppcoreguidelines-avoid-do-while",
    "cppcoreguidelines-pro-bounds-avoid-unchecked-container-access",
    "performance-no-int-to-ptr",
    "cppcoreguidelines-avoid-non-const-global-variables",
    "cppcoreguidelines-owning-memory",
    "cppcoreguidelines-no-malloc",
    "hicpp-no-malloc",
    "misc-include-cleaner",
}

WARN = re.compile(r"^(?P<file>/[^:]+):(?P<line>\d+):\d+: warning: (?P<msg>.*?) \[(?P<checks>[a-z0-9,.-]+)\]$")
NAMING = re.compile(r"invalid case style for (?P<kind>.+?) '(?P<name>[^']+)'")

out_dir = pathlib.Path(sys.argv[1])
root = pathlib.Path(sys.argv[2])

per_check = collections.Counter()
per_dir = collections.Counter()
naming = collections.defaultdict(set)
seen = set()

for raw in (out_dir / "tidy.txt").read_text(errors="replace").splitlines():
    m = WARN.match(raw.strip())
    if not m:
        continue
    key = (m["file"], m["line"], m["checks"])
    if key in seen:            # run-clang-tidy repeats header diagnostics per TU
        continue
    seen.add(key)

    try:
        rel = pathlib.Path(m["file"]).relative_to(root)
    except ValueError:
        continue               # outside the repo, ignore
    per_dir[rel.parts[0]] += 1
    for check in m["checks"].split(","):
        per_check[check] += 1

    n = NAMING.search(m["msg"])
    if n:
        naming[n["kind"]].add(n["name"])

# Reserved __X__ include guards, listed separately since the fix is mechanical.
guards = subprocess.run(
    ["git", "grep", "-l", "-E", r"^#ifndef __[A-Z0-9_]+__$", "--", "*.h"],
    cwd=root, capture_output=True, text=True,
).stdout.split()

churn = []
churn_path = out_dir / "format-churn.txt"
if churn_path.exists():
    for line in churn_path.read_text().splitlines():
        count, _, name = line.partition("\t")
        churn.append((int(count), name))

L = []
w = L.append

w("# Style adoption report\n")
w("Generated by `just lint-report`. Nothing has been applied to the tree — this is the")
w("full set of violations the new `.clang-format` and `.clang-tidy` would produce, so the")
w("rules can be argued with before any code moves.\n")

w("## clang-format\n")
w(f"- files that would change: **{len(churn)}**")
w(f"- total changed lines: **{sum(c for c, _ in churn)}**")
w(f"- full diff: `build/lint/format.diff`\n")
w("Highest-churn files:\n")
w("| lines | file |")
w("|------:|------|")
for count, name in churn[:15]:
    w(f"| {count} | `{name}` |")
w("")

w("## clang-tidy\n")
w(f"Total findings: **{sum(per_dir.values())}** across {len(per_dir)} top-level directories.\n")

w("### Findings per check\n")
w("| count | check | bare-metal suspect |")
w("|------:|-------|:------------------:|")
for check, count in per_check.most_common():
    w(f"| {count} | `{check}` | {'yes' if check in BARE_METAL_SUSPECTS else ''} |")
w("")

w("### Findings per directory\n")
w("| count | directory |")
w("|------:|-----------|")
for d, count in per_dir.most_common():
    w(f"| {count} | `{d}/` |")
w("")

w("### Candidates for the exclusion list\n")
w("High-count checks that look inherent to bare-metal code rather than fixable. Decide")
w("whether each belongs in the EL2 delta block in `.clang-tidy`.\n")
suspects = [(c, n) for c, n in per_check.most_common() if c in BARE_METAL_SUSPECTS]
if suspects:
    for check, count in suspects:
        w(f"- `{check}` — {count}")
else:
    w("_None; the current exclusion list already covers them._")
w("")

w("### Naming violations by identifier kind\n")
w("This is where changing the rule is often better than changing the code.\n")
if naming:
    for kind in sorted(naming, key=lambda k: -len(naming[k])):
        names = sorted(naming[kind])
        w(f"**{kind}** — {len(names)}\n")
        w("```")
        w("\n".join(names))
        w("```\n")
else:
    w("_No naming violations._\n")

w("### Reserved include guards\n")
w(f"{len(guards)} headers use implementation-reserved `__X__` guards")
w("(`bugprone-reserved-identifier`, `cert-dcl37-c`, `cert-dcl51-cpp`).")
w("Mechanical rename to `HYPERBERRY_<PATH>_H_`.\n")
for g in guards:
    w(f"- `{g}`")
w("")

(out_dir / "SUMMARY.md").write_text("\n".join(L))
