set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

find_program(HB_CLANG NAMES clang-22 clang REQUIRED)
find_program(HB_CLANGXX NAMES clang++-22 clang++ REQUIRED)

set(CMAKE_C_COMPILER ${HB_CLANG})
set(CMAKE_CXX_COMPILER ${HB_CLANGXX})
set(CMAKE_ASM_COMPILER ${HB_CLANG})

set(CMAKE_C_COMPILER_TARGET aarch64-none-elf)
set(CMAKE_CXX_COMPILER_TARGET aarch64-none-elf)
set(CMAKE_ASM_COMPILER_TARGET aarch64-none-elf)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_LINKER lld)
