#!/usr/bin/env python3
"""Turn the offset markers in compiled assembly into a header of #defines.

A C++ file emits `.ascii "->NAME VALUE"` for each offset through inline asm.
Compiled with -S, those strings land in the assembly text verbatim. This script
collects them into a header that assembly sources can #include, so the offsets
they index with come from the compiler rather than from a hand kept copy.
"""

import argparse
import pathlib
import re
import sys

MARKER = re.compile(r'"->(\w+) #?(-?\d+)"')


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--in", dest="source", required=True, type=pathlib.Path)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    args = parser.parse_args()

    offsets = MARKER.findall(args.source.read_text())
    if not offsets:
        print(f"asmoffsets: no markers in {args.source}", file=sys.stderr)
        return 1

    guard = "__" + re.sub(r"\W", "_", args.out.name).upper() + "__"
    lines = [
        f"// Generated by scripts/asmoffsets/asmoffsets.py from {args.source.name}. Do not edit.",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        *(f"#define {name} {int(value)}" for name, value in offsets),
        "",
        f"#endif // {guard}",
        "",
    ]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
